server=1
daemon=0
disablewallet=1
prune=0
txindex=0
zmqpubnevm=
dbcache=768
par=2
maxconnections=16
maxmempool=100
listen=0
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=8370
rpcworkqueue=32
shrinkdebugfile=1
