server {
    listen 80;
    listen [::]:80;
    server_name tracker.syscoin.dev;
    root /var/www/html;

    location /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location /syswallettracker/ {
        try_files $uri =404;
        autoindex off;
        add_header Cache-Control "public, max-age=30" always;
        add_header X-Content-Type-Options nosniff always;
    }

    location / {
        return 404;
    }
}
